"""Cognito token endpoint client.

All three public functions share _call_token_endpoint to avoid duplication.
client_id, client_secret, and token_endpoint are read from environment / SSM
at cold-start and cached for the lifetime of the Lambda container.
"""
import json
import os
import urllib.parse
import urllib.request
from base64 import b64encode
from typing import Any

import boto3
from aws_lambda_powertools import Logger

logger = Logger(service="coquito-cognito-service")

# ---------------------------------------------------------------------------
# Cold-start configuration (cached across warm invocations)
# ---------------------------------------------------------------------------
_client_secret: str | None = None


def _get_client_secret() -> str:
    """Read client secret from SSM on first call; return cached value thereafter."""
    global _client_secret  # noqa: PLW0603
    if _client_secret is None:
        ssm_path = os.environ["SSM_CLIENT_SECRET"]
        ssm = boto3.client("ssm")
        response = ssm.get_parameter(Name=ssm_path, WithDecryption=True)
        _client_secret = response["Parameter"]["Value"]
    return _client_secret


def _get_config() -> tuple[str, str, str]:
    """Return (client_id, client_secret, token_endpoint)."""
    return (
        os.environ["COGNITO_CLIENT_ID"],
        _get_client_secret(),
        os.environ["TOKEN_ENDPOINT"],
    )


# ---------------------------------------------------------------------------
# Internal shared implementation
# ---------------------------------------------------------------------------
def _call_token_endpoint(params: dict[str, str]) -> dict[str, Any]:
    """POST to the Cognito /oauth2/token endpoint and return the parsed response.

    Uses HTTP Basic Auth (client_id:client_secret) as required for confidential clients.
    Raises RuntimeError if Cognito returns an error field.
    """
    client_id, client_secret, token_endpoint = _get_config()

    credentials = b64encode(f"{client_id}:{client_secret}".encode()).decode()
    body = urllib.parse.urlencode(params).encode()

    req = urllib.request.Request(
        token_endpoint,
        data=body,
        headers={
            "Content-Type": "application/x-www-form-urlencoded",
            "Authorization": f"Basic {credentials}",
        },
        method="POST",
    )

    with urllib.request.urlopen(req, timeout=10) as resp:  # noqa: S310
        data = json.loads(resp.read())

    if "error" in data:
        raise RuntimeError(f"{data['error']}: {data.get('error_description', '')}")

    return data


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
def exchange_code(code: str, redirect_uri: str, code_verifier: str) -> dict[str, Any]:
    """Exchange an authorization code for id_token, access_token, refresh_token.

    Args:
        code: Authorization code from Cognito Managed Login callback.
        redirect_uri: Must match the callback URL registered on the app client.
        code_verifier: PKCE code verifier generated by the SPA.

    Returns:
        Dict with id_token, access_token, refresh_token, expires_in.
    """
    return _call_token_endpoint(
        {
            "grant_type": "authorization_code",
            "code": code,
            "redirect_uri": redirect_uri,
            "code_verifier": code_verifier,
        }
    )


def refresh_tokens(refresh_token: str) -> dict[str, Any]:
    """Exchange a refresh token for new id_token and access_token.

    Args:
        refresh_token: The refresh_token cookie value from the client.

    Returns:
        Dict with id_token, access_token, expires_in (no new refresh_token).
    """
    return _call_token_endpoint(
        {
            "grant_type": "refresh_token",
            "refresh_token": refresh_token,
        }
    )


def revoke_token(refresh_token: str) -> None:
    """Revoke a refresh token at the Cognito /oauth2/revoke endpoint.

    Best-effort: callers should log but not fail on errors.

    Args:
        refresh_token: The refresh_token to revoke.
    """
    client_id, client_secret, token_endpoint = _get_config()
    revoke_url = token_endpoint.replace("/oauth2/token", "/oauth2/revoke")
    credentials = b64encode(f"{client_id}:{client_secret}".encode()).decode()
    body = urllib.parse.urlencode({"token": refresh_token, "client_id": client_id}).encode()

    req = urllib.request.Request(
        revoke_url,
        data=body,
        headers={
            "Content-Type": "application/x-www-form-urlencoded",
            "Authorization": f"Basic {credentials}",
        },
        method="POST",
    )

    with urllib.request.urlopen(req, timeout=10) as resp:  # noqa: S310
        resp.read()
